apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-web-pipeline
  namespace: hello-web-namespace
spec:
  params:
    - name: url
      description: The Git repository URL to build
      type: string
    - name: revision
      description: The Git revision (branch, tag, SHA) to clone
      type: string
      default: main
    - name: commit-sha
      description: The commit SHA for tagging the image
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: "$(params.url)"
        - name: revision
          value: "$(params.revision)"
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: extract-short-sha
      taskSpec:
        params:
          - name: commit-sha
            type: string
        results:
          - name: short-sha
            description: The shortened commit SHA
        steps:
          - name: extract-sha
            image: alpine
            script: |
              SHORT_SHA=$(echo "$(params.commit-sha)" | cut -c1-7)
              echo -n "$SHORT_SHA" > $(results.short-sha.path)
      params:
        - name: commit-sha
          value: "$(params.commit-sha)"

    - name: build-and-push
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: "quay.io/paulcapestany/hello-web:$(tasks.extract-short-sha.results.short-sha)"
        - name: STORAGE_DRIVER
          value: "vfs"
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - extract-short-sha
