apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-web-pipeline
  namespace: hello-web-namespace
spec:
  params:
    - name: url
      description: The Git repository URL to build
      type: string
    - name: revision
      description: The Git revision (branch, tag, SHA) to clone
      type: string
      default: main
    - name: image-url
      description: The full image URL (including tag) to push the built image to
      type: string
    - name: commit-sha
      description: The shortened commit SHA for tagging the image
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: "$(params.url)"
        - name: revision
          value: "$(params.revision)"
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: build-and-push
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: "$(params.image-url)"
        - name: STORAGE_DRIVER
          value: "vfs"
      workspaces:
        - name: source
          workspace: shared-workspace
