apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-web-pipeline
  namespace: hello-web-namespace
spec:
  params:
    - name: url
      description: The Git repository URL to build
      type: string
    - name: revision
      description: The Git revision (branch, tag, SHA) to clone
      type: string
      default: main
    - name: commit-sha
      description: The commit SHA for tagging the image
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: fetch-repository
      params:
        - name: url
          value: "$(params.url)"
        - name: revision
          value: "$(params.revision)"
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: extract-short-sha
      taskRef:
        name: extract-short-sha
      params:
        - name: commit-sha
          value: "$(params.commit-sha)"

    - name: build-and-push
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: "quay.io/paulcapestany/hello-web:$(tasks.extract-short-sha.results.short-sha)"
        - name: STORAGE_DRIVER
          value: "vfs"
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - extract-short-sha
