apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: hello-web-pipelinerun
  namespace: hello-web-namespace
spec:
  pipelineRef:
    name: hello-web-pipeline
  serviceAccountName: pipeline
  params:
    - name: url
      value: https://github.com/paulcapestany/hello-web.git
    - name: revision
      value: main
    - name: commit-sha
      value: "9daa0625158b54be441509e082f99b9b2f508a93"
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: hello-web-pvc
