apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: hello-web-pipelinerun-
  namespace: hello-web-namespace
spec:
  pipelineRef:
    name: hello-web-pipeline
  serviceAccountName: pipeline
  params:
    - name: url
      value: https://github.com/paulcapestany/hello-web.git
    - name: revision
      value: main
    - name: commit-sha
      value: "aa60068321248a07504ab5ba5b2e3b1a94ae5291"
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: hello-web-pvc
