apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: hello-web-pipelinerun-template
  namespace: hello-web-namespace
spec:
  params:
    - name: url
      description: The Git repository URL to build
    - name: image-url
      description: The full image URL (including tag) to push the built image to
    - name: commit-sha
      description: The shortened commit SHA for tagging the image
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: hello-web-pipelinerun-
        namespace: hello-web-namespace
      spec:
        pipelineRef:
          name: hello-web-pipeline
        serviceAccountName: pipeline
        params:
          - name: url
            value: "$(params.url)"
          - name: image-url
            value: "$(params.image-url)"
          - name: commit-sha
            value: "$(params.commit-sha)"
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: hello-web-pvc
