apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: hello-web-trigger-binding
  namespace: hello-web-namespace
spec:
  params:
    - name: url
      value: "$(body.repository.clone_url)"
    - name: image-url
      value: "quay.io/paulcapestany/hello-web:$(extensions.short_sha)"
    - name: commit-sha
      value: "$(extensions.short_sha)"
