apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: hello-web-trigger-binding
  namespace: hello-web-namespace
spec:
  params:
    - name: git-url
      value: "$(body.repository.clone_url)"
    - name: commit-sha
      value: "$(body.head_commit.id[0:7])" # Shortened commit SHA
