apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-web
  namespace: openshift-gitops
  annotations:
    argocd-image-updater.argoproj.io/image-list: hello-web=quay.io/paulcapestany/hello-web
    argocd-image-updater.argoproj.io/hello-web.update-strategy: latest
    argocd-image-updater.argoproj.io/hello-web.tag-match: "^[a-f0-9]{7}$" # Match 7-character commit hashes
    argocd-image-updater.argoproj.io/write-back-method: git:secret
    argocd-image-updater.argoproj.io/git-user: "ci-bot"
    argocd-image-updater.argoproj.io/git-email: "ci-bot@example.com"    
spec:
  project: default
  source:
    repoURL: 'https://github.com/paulcapestany/hello-gitops.git'
    targetRevision: HEAD
    path: apps/hello-web
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hello-web-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true