apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: hello-web-namespace
  name: argocd-application-controller-role
rules:
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["create", "update", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "update", "get", "list", "watch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "update", "get", "list", "watch", "delete"]